### ISSUE TITLE
progress information?

### ISSUE THREAD

**Issue by hydrargyrum** [suntong/ffcvt#29]
It would be nice if ffcvt reported some progress information to stdout. Can it know how many input bytes were processed by ffmpeg? Or can it parse ffmpeg's debug output?

**Comment by suntong** [comment]
Yep, that's what I wanted too.

Catching ffmpeg's output has already been improved once, but I'll take another look if I have some time.

Don't get your hope up thought, as last time when I looked at it, the previous improvement was the best I could do...

**Comment by suntong** [comment]
I use ffcvt mostly to convert my TV series, and I found that once the first conversion was done, the remaining time estimate given by ffcvt was pretty accurate, so I never bother to look further.

**Comment by suntong** [comment]
Finally found out how to do that, however, I won't add this feature to ffcvt because, 

- Looking at the implementation details from [transcoder](https://github.com/floostack/transcoder/), I view it as too much coding for too little value, because
- My normal conversion time are in hours, depending on the input sources, the conversion time of different files are about two to six hours. At such progress rate, I'll only check back after the estimated time, instead of watching the progress inching ahead. IE such progress information is basically useless ***to me***. 
- The remaining time estimation has been improved in [v1.9.0](https://github.com/suntong/ffcvt/releases/tag/v1.9.0), so now, even if the input files are not TV series, but are changing their sizes dramatically, the time estimation will still be pretty accurate.

Overall, as the conversion time is about two to six hours, by-the-second progress information is meaningless ***to me***, so this feature will never be added to ffcvt. Thus closing it as "won't fix".

If you want, you can use [transcoder](https://github.com/floostack/transcoder/) instead.
